---
CustSetup:
  - CustName: DANS
    CustCRM: 312703
    CustUntrustVlan: 3000
    CustTrustVlan: 3001

ApplicationSetup:
  - ApplicationProto: UDP
    ApplicationPort: 161

RuleSetup:
  - RuleSrc: all
    RuleDst: 10.10.10.10/32
    RuleApplication: SNMP
    RuleAction: Permit

AddressSetup:
  - AddressName: 10.10.10.10/32
    AddressIP: 10.10.10.10/32

NatSetup:
  - NatSource:
    NatSourcePool:
    NatDestPublicIP:
    NatDestPrivateIP:
    NatDestPublicPort:
    NatDestPrivatePort:
    NatStaticPublicIP:
    NatStaticPrivateIP: